version: 0.2

phases:
  build:
   commands:
    - echo Entered into the build phase
    - mvn clean package
  post_build:
   commands:
    - echo build completed successfully
artifacts:
  files:
   - target/hello-world.jar
  discard-paths: yes